channels:
- conda-forge
dependencies:
- python=3.10.0
- pip<=21.2.3
- pip:
  - mlflow==2.15.0
  - cffi==1.16.0
  - cloudpickle==3.0.0
  - lightgbm==4.5.0
  - matplotlib==3.10.7
  - numpy==1.26.4
  - pandas==2.2.2
  - psutil==6.0.0
  - pyarrow==15.0.2
  - scikit-learn==1.7.2
  - scipy==1.14.0
name: mlflow-env
